catalogMode: prefer

minimumReleaseAge: 10080
shellEmulator: true
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 43200

packages:
  - docs
  - packages/**/*

catalog:
  "@antfu/eslint-config": ^9.0.0
  "@antfu/ni": ^30.1.0
  "@babel/types": ^7.29.7
  "@iconify/json": ^2.2.488
  "@intlify/unplugin-vue-i18n": ^11.2.4
  "@shikijs/markdown-it": ^4.2.0
  "@tanstack/vue-query": ^5.101.0
  "@types/chroma-js": ^3.1.2
  "@types/color-diff": ^1.2.5
  "@types/file-saver": ^2.0.7
  "@types/lodash": ^4.17.24
  "@types/markdown-it-link-attributes": ^3.0.5
  "@types/node": ^25.9.4
  "@types/nprogress": ^0.2.3
  "@types/papaparse": ^5.5.2
  "@typescript-eslint/eslint-plugin": ^8.61.1
  "@typescript-eslint/parser": ^8.61.1
  "@unhead/vue": ^3.1.4
  "@unocss/eslint-config": ^66.7.2
  "@unocss/reset": ^66.7.2
  "@vitejs/plugin-vue": ^6.0.7
  "@vue-macros/volar": ^3.1.2
  "@vue/test-utils": ^2.4.11
  "@vueuse/components": ^14.3.0
  "@vueuse/core": ^14.3.0
  "@vueuse/router": ^14.3.0
  bumpp: ^11.1.0
  chroma-js: ^3.2.0
  color-diff: ^1.4.0
  critters: ^0.0.25
  cross-env: ^10.1.0
  cypress: ^15.17.0
  cypress-vite: ^1.10.1
  dayjs: ^1.11.21
  eslint: ^10.5.0
  eslint-plugin-cypress: ^6.4.1
  eslint-plugin-format: ^2.0.1
  esmo: ^4.8.0
  file-saver: ^2.0.5
  floating-vue: 5.2.2
  flowbite: ^4.0.2
  fsxx: ^0.1.0
  git-repo-info: ^2.1.1
  glob: ^13.0.6
  gsap: ^3.15.0
  highcharts: ^13.0.0
  highcharts-vue: ^2.0.1
  hls.js: ^1.6.16
  https-localhost: ^4.7.1
  js-base64: ^3.7.8
  less: ^4.6.6
  lodash: ^4.18.1
  markdown-it-link-attributes: ^4.0.1
  npm-run-all: ^4.1.5
  nprogress: ^0.2.0
  ordinal: ^1.0.3
  papaparse: ^5.5.4
  pinia: ^3.0.4
  rollup: ^4.62.2
  shiki: ^4.2.0
  sleep-promise: ^9.1.0
  string-width: ^8.2.1
  taze: ^19.14.1
  typescript: ^6.0.3
  unbuild: ^3.6.1
  unocss: ^66.7.2
  unplugin-auto-import: ^21.0.0
  unplugin-vue-components: ^32.1.0
  unplugin-vue-macros: ^2.14.5
  unplugin-vue-markdown: ^32.0.0
  unplugin-vue-router: ^0.18.0
  vite: ^8.0.16
  vite-bundle-visualizer: ^1.2.1
  vite-plugin-html: ^3.2.2
  vite-plugin-inspect: ^11.4.1
  vite-plugin-vue-devtools: ^8.1.3
  vite-plugin-vue-layouts: ^0.11.0
  vite-plugin-webfont-dl: ^3.12.0
  vite-ssg: ^28.3.0
  vite-ssg-sitemap: ^0.10.0
  vitepress: ^2.0.0-alpha.17
  vitepress-plugin-group-icons: ^1.7.5
  vitest: ^4.1.9
  vue: ^3.5.38
  vue-demi: ^0.14.10
  vue-i18n: ^11.4.6
  vue-router: ^5.1.0
  vue-search-select: ^3.2.0
  vue-toast-notification: ^3.1.3
  vue-tsc: ^3.3.5
  xlsx-js-style: ^1.2.0
  zx: ^8.8.5

allowBuilds:
  cypress: false
  esbuild: false
  vue-demi: false
