catalogMode: prefer

shellEmulator: true
trustPolicy: no-downgrade

packages:
  - docs
  - packages/**/*

catalog:
  "@antfu/eslint-config": ^6.7.3
  "@antfu/ni": ^27.0.1
  "@babel/types": ^7.29.0
  "@iconify/json": ^2.2.438
  "@intlify/unplugin-vue-i18n": ^11.0.3
  "@shikijs/markdown-it": ^3.22.0
  "@tanstack/vue-query": ^5.92.9
  "@types/chroma-js": ^3.1.2
  "@types/color-diff": ^1.2.5
  "@types/file-saver": ^2.0.7
  "@types/lodash": ^4.17.23
  "@types/markdown-it-link-attributes": ^3.0.5
  "@types/node": ^24.10.13
  "@types/nprogress": ^0.2.3
  "@types/papaparse": ^5.5.2
  "@typescript-eslint/eslint-plugin": ^8.55.0
  "@typescript-eslint/parser": ^8.55.0
  "@unhead/vue": ^2.1.4
  "@unocss/eslint-config": ^66.6.0
  "@unocss/reset": ^66.6.0
  "@vitejs/plugin-vue": ^6.0.4
  "@vue-macros/volar": ^3.1.2
  "@vue/test-utils": ^2.4.6
  "@vueuse/components": ^14.2.1
  "@vueuse/core": ^14.2.1
  "@vueuse/router": ^14.2.1
  bumpp: ^10.4.1
  chroma-js: ^3.2.0
  color-diff: ^1.4.0
  critters: ^0.0.25
  cross-env: ^10.1.0
  cypress: ^15.10.0
  cypress-vite: ^1.8.0
  dayjs: ^1.11.19
  eslint: ^9.39.2
  eslint-plugin-cypress: ^5.3.0
  eslint-plugin-format: ^1.4.0
  esmo: ^4.8.0
  file-saver: ^2.0.5
  floating-vue: 5.2.2
  flowbite: ^4.0.1
  fsxx: ^0.1.0
  git-repo-info: ^2.1.1
  glob: ^13.0.2
  gsap: ^3.14.2
  highcharts: ^12.5.0
  highcharts-vue: ^2.0.1
  hls.js: ^1.6.15
  https-localhost: ^4.7.1
  js-base64: ^3.7.8
  less: ^4.5.1
  lodash: ^4.17.23
  markdown-it-link-attributes: ^4.0.1
  npm-run-all: ^4.1.5
  nprogress: ^0.2.0
  ordinal: ^1.0.3
  papaparse: ^5.5.3
  pinia: ^3.0.4
  pnpm: ^10.29.3
  rollup: ^4.57.1
  shiki: ^3.22.0
  sleep-promise: ^9.1.0
  string-width: ^8.1.1
  taze: ^19.9.2
  typescript: ^5.9.3
  unbuild: ^3.6.1
  unocss: ^66.6.0
  unplugin-auto-import: ^20.3.0
  unplugin-vue-components: ^30.0.0
  unplugin-vue-macros: ^2.14.5
  unplugin-vue-markdown: ^29.2.0
  unplugin-vue-router: ^0.18.0
  vite: ^7.3.1
  vite-bundle-visualizer: ^1.2.1
  vite-plugin-html: ^3.2.2
  vite-plugin-inspect: ^11.3.3
  vite-plugin-vue-devtools: ^8.0.6
  vite-plugin-vue-layouts: ^0.11.0
  vite-plugin-webfont-dl: ^3.11.1
  vite-ssg: ^28.3.0
  vite-ssg-sitemap: ^0.10.0
  vitepress: ^2.0.0-alpha.16
  vitepress-plugin-group-icons: ^1.7.1
  vitest: ^4.0.18
  vue: ^3.5.28
  vue-demi: ^0.14.10
  vue-i18n: ^11.2.8
  vue-router: ^4.6.4
  vue-search-select: ^3.2.0
  vue-toast-notification: ^3.1.3
  vue-tsc: ^3.2.4
  xlsx-js-style: ^1.2.0
  zx: ^8.8.5

ignoredBuiltDependencies:
  - cypress
