packages:
  - "packages/**/*"
catalog:
  "@antfu/eslint-config": ^4.11.0
  "@antfu/ni": ^24.3.0
  "@babel/types": ^7.27.0
  "@iconify/json": ^2.2.321
  "@intlify/unplugin-vue-i18n": ^5.3.1
  "@shikijs/markdown-it": ^1.29.2
  "@tanstack/vue-query": ^5.70.0
  "@types/chroma-js": ^2.4.5
  "@types/color-diff": ^1.2.5
  "@types/file-saver": ^2.0.7
  "@types/glob": ^8.1.0
  "@types/lodash": ^4.17.16
  "@types/markdown-it-link-attributes": ^3.0.5
  "@types/node": ^18.19.84
  "@types/nprogress": ^0.2.3
  "@types/papaparse": ^5.3.15
  "@typescript-eslint/eslint-plugin": ^8.28.0
  "@typescript-eslint/parser": ^8.28.0
  "@unhead/vue": ^1.11.20
  "@unocss/eslint-config": ^66.0.0
  "@unocss/reset": ^66.0.0
  "@vitejs/plugin-vue": ^5.2.3
  "@vue-macros/volar": ^0.30.15
  "@vue/test-utils": ^2.4.6
  "@vueuse/components": ^11.3.0
  "@vueuse/core": ^11.3.0
  "@vueuse/head": ^2.0.0
  "@vueuse/router": ^11.3.0
  bumpp: ^10.1.0
  chroma-js: ^3.1.2
  color-diff: ^1.4.0
  critters: ^0.0.25
  cross-env: ^7.0.3
  cypress: ^14.2.1
  cypress-vite: ^1.6.0
  dayjs: ^1.11.13
  eslint: ^9.23.0
  eslint-plugin-cypress: ^4.2.0
  eslint-plugin-format: ^1.0.1
  esmo: ^4.8.0
  file-saver: ^2.0.5
  floating-vue: 5.2.2
  flowbite: ^3.1.2
  fsxx: ^0.1.0
  git-repo-info: ^2.1.1
  glob: ^11.0.1
  gsap: ^3.12.7
  highcharts: ^12.1.2
  highcharts-vue: ^2.0.1
  https-localhost: ^4.7.1
  js-base64: ^3.7.7
  less: ^4.2.2
  lodash: ^4.17.21
  markdown-it-link-attributes: ^4.0.1
  npm-run-all: ^4.1.5
  nprogress: ^0.2.0
  ordinal: ^1.0.3
  papaparse: ^5.5.2
  pinia: ^3.0.1
  pnpm: ^10.7.0
  rollup: ^4.38.0
  shiki: ^3.2.1
  sleep-promise: ^9.1.0
  string-width: ^7.2.0
  taze: ^19.0.4
  typescript: ^5.8.2
  unbuild: ^2.0.0
  unocss: ^66.0.0
  unplugin-auto-import: ^0.18.6
  unplugin-vue-components: ^0.27.5
  unplugin-vue-macros: ^2.14.5
  unplugin-vue-markdown: ^0.26.3
  unplugin-vue-router: ^0.10.9
  vite: ^5.4.15
  vite-bundle-visualizer: ^1.2.1
  vite-plugin-html: ^3.2.2
  vite-plugin-inspect: ^0.8.9
  vite-plugin-pwa: ^0.20.5
  vite-plugin-vue-devtools: ^7.7.2
  vite-plugin-vue-layouts: ^0.11.0
  vite-plugin-webfont-dl: ^3.10.4
  vite-ssg: ^0.23.8
  vite-ssg-sitemap: ^0.8.1
  vitest: ^3.0.9
  vue: ^3.5.13
  vue-demi: ^0.14.10
  vue-i18n: ^10.0.6
  vue-router: ^4.5.0
  vue-search-select: ^3.2.0
  vue-toast-notification: ^3.1.3
  vue-tsc: ^2.2.8
  workbox-build: ^7.3.0
  workbox-window: ^7.3.0
  xlsx-js-style: ^1.2.0
  zx: ^8.4.1
