// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  banner: string;
  'banner-img': string;
  loading: string;
  root: string;
  title: string;
}
export const cssExports: CssExports;
export default cssExports;
