// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  BalloonTable: string;
  loading: string;
  touch: string;
}
export const cssExports: CssExports;
export default cssExports;
