// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  FINISHED: string;
  FROZEN: string;
  PENDING: string;
  RUNNING: string;
  'am-active': string;
  'am-progress': string;
  'am-progress-bar': string;
  'am-progress-bar-danger': string;
  'am-progress-bar-secondary': string;
  'am-progress-bar-success': string;
  'am-progress-bar-warning': string;
  'am-progress-cursor': string;
  'am-progress-sm': string;
  'am-progress-striped': string;
  'am-progress-xs': string;
  'bs-tether-element-attached-bottom': string;
  'bs-tether-element-attached-left': string;
  'bs-tether-element-attached-right': string;
  'bs-tether-element-attached-top': string;
  in: string;
  label: string;
  'progress-bar-stripes': string;
  tooltip: string;
  'tooltip-bottom': string;
  'tooltip-inner': string;
  'tooltip-left': string;
  'tooltip-right': string;
  'tooltip-top': string;
}
export const cssExports: CssExports;
export default cssExports;
