// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'MuiIconButton-label': string;
  'MuiIconButton-root': string;
  'border-bottom': string;
  go: string;
  loading: string;
  'm-box': string;
  'm-title': string;
  root: string;
}
export const cssExports: CssExports;
export default cssExports;
