import { describe, expect, it } from "vitest";
import { resolve } from "node:path";
import fs from "fs";

import { createContest } from "../src/contest";
import { createTeams } from "../src/team";
import { createSubmissions } from "../src/submission";
import { Rank } from "../src/rank";

describe("contest", () => {
  it("2023_ccpc_final", () => {
    const contestData = fs.readFileSync(resolve(__dirname, "test-data/2023_ccpc_final/config.json"));
    const teamData = fs.readFileSync(resolve(__dirname, "test-data/2023_ccpc_final/team.json"));
    const runData = fs.readFileSync(resolve(__dirname, "test-data/2023_ccpc_final/run.json"));

    const contestJSON = JSON.parse(contestData.toString());
    const teamJSON = JSON.parse(teamData.toString());
    const runJSON = JSON.parse(runData.toString());

    const contest = createContest(contestJSON);
    const teams = createTeams(teamJSON);
    const submissions = createSubmissions(runJSON);

    const rank = new Rank(contest, teams, submissions);
    rank.buildRank();

    expect(rank.firstSolvedSubmissions).toMatchInlineSnapshot(`
      Map {
        "0" => [
          Submission {
            "id": "68",
            "isIgnore": false,
            "problemId": "0",
            "status": "CORRECT",
            "teamId": "3000202305140102",
            "timestamp": 720,
          },
        ],
        "1" => [
          Submission {
            "id": "920",
            "isIgnore": false,
            "problemId": "1",
            "status": "CORRECT",
            "teamId": "3000202305140047",
            "timestamp": 10920,
          },
        ],
        "2" => [
          Submission {
            "id": "165",
            "isIgnore": false,
            "problemId": "2",
            "status": "CORRECT",
            "teamId": "3000202305140063",
            "timestamp": 1800,
          },
        ],
        "3" => [
          Submission {
            "id": "787",
            "isIgnore": false,
            "problemId": "3",
            "status": "CORRECT",
            "teamId": "3000202305140103",
            "timestamp": 8700,
          },
        ],
        "4" => [
          Submission {
            "id": "0",
            "isIgnore": false,
            "problemId": "4",
            "status": "CORRECT",
            "teamId": "3000202305140002",
            "timestamp": 240,
          },
        ],
        "5" => [
          Submission {
            "id": "121",
            "isIgnore": false,
            "problemId": "5",
            "status": "CORRECT",
            "teamId": "3000202305140047",
            "timestamp": 1200,
          },
        ],
        "6" => [],
        "7" => [
          Submission {
            "id": "685",
            "isIgnore": false,
            "problemId": "7",
            "status": "CORRECT",
            "teamId": "3000202305140047",
            "timestamp": 7680,
          },
        ],
        "8" => [
          Submission {
            "id": "903",
            "isIgnore": false,
            "problemId": "8",
            "status": "CORRECT",
            "teamId": "3000202305140046",
            "timestamp": 10560,
          },
        ],
        "9" => [
          Submission {
            "id": "146",
            "isIgnore": false,
            "problemId": "9",
            "status": "CORRECT",
            "teamId": "3000202305140046",
            "timestamp": 1440,
          },
        ],
        "10" => [
          Submission {
            "id": "1164",
            "isIgnore": false,
            "problemId": "10",
            "status": "CORRECT",
            "teamId": "3000202305140047",
            "timestamp": 14280,
          },
        ],
        "11" => [
          Submission {
            "id": "201",
            "isIgnore": false,
            "problemId": "11",
            "status": "CORRECT",
            "teamId": "3000202305140027",
            "timestamp": 2340,
          },
        ],
        "12" => [
          Submission {
            "id": "347",
            "isIgnore": false,
            "problemId": "12",
            "status": "CORRECT",
            "teamId": "3000202305140046",
            "timestamp": 3660,
          },
        ],
      }
    `);

    expect(rank.teams[0].rank).toMatchInlineSnapshot("1");
    expect(rank.teams[0].solvedProblemNum).toMatchInlineSnapshot("11");
    expect(rank.teams[0].penalty).toMatchInlineSnapshot("89820");
    expect(rank.teams[0].name).toMatchInlineSnapshot('"重生之我是菜狗"');
    expect(rank.teams[0].organization).toMatchInlineSnapshot('"北京大学"');
    expect(rank.teams[0].problemStatistics).toMatchInlineSnapshot(`
      [
        TeamProblemStatistics {
          "failedCount": 0,
          "ignoreCount": 0,
          "isFirstSolved": false,
          "isSolved": true,
          "pendingCount": 0,
          "problem": Problem {
            "balloonColor": {
              "background_color": "rgba(189, 14, 14, 0.7)",
              "color": "#fff",
            },
            "id": "0",
            "label": "A",
            "memoryLimit": undefined,
            "name": "",
            "statistics": {
              "acceptedNum": 29,
              "pendingNum": 0,
              "rejectedNum": 178,
              "submittedNum": 207,
            },
            "timeLimit": undefined,
          },
          "solvedTimestamp": 960,
          "submissions": [
            Submission {
              "id": "98",
              "isIgnore": false,
              "problemId": "0",
              "status": "CORRECT",
              "teamId": "3000202305140047",
              "timestamp": 960,
            },
          ],
        },
        TeamProblemStatistics {
          "failedCount": 2,
          "ignoreCount": 0,
          "isFirstSolved": true,
          "isSolved": true,
          "pendingCount": 0,
          "problem": Problem {
            "balloonColor": {
              "background_color": "#951FD9",
              "color": "#fff",
            },
            "id": "1",
            "label": "B",
            "memoryLimit": undefined,
            "name": "",
            "statistics": {
              "acceptedNum": 3,
              "pendingNum": 0,
              "rejectedNum": 12,
              "submittedNum": 15,
            },
            "timeLimit": undefined,
          },
          "solvedTimestamp": 10920,
          "submissions": [
            Submission {
              "id": "877",
              "isIgnore": false,
              "problemId": "1",
              "status": "REJECTED",
              "teamId": "3000202305140047",
              "timestamp": 10020,
            },
            Submission {
              "id": "890",
              "isIgnore": false,
              "problemId": "1",
              "status": "REJECTED",
              "teamId": "3000202305140047",
              "timestamp": 10320,
            },
            Submission {
              "id": "920",
              "isIgnore": false,
              "problemId": "1",
              "status": "CORRECT",
              "teamId": "3000202305140047",
              "timestamp": 10920,
            },
          ],
        },
        TeamProblemStatistics {
          "failedCount": 0,
          "ignoreCount": 0,
          "isFirstSolved": false,
          "isSolved": true,
          "pendingCount": 0,
          "problem": Problem {
            "balloonColor": {
              "background_color": "rgba(255, 255, 255, 0.7)",
              "color": "#000",
            },
            "id": "2",
            "label": "C",
            "memoryLimit": undefined,
            "name": "",
            "statistics": {
              "acceptedNum": 99,
              "pendingNum": 0,
              "rejectedNum": 161,
              "submittedNum": 263,
            },
            "timeLimit": undefined,
          },
          "solvedTimestamp": 4800,
          "submissions": [
            Submission {
              "id": "438",
              "isIgnore": false,
              "problemId": "2",
              "status": "CORRECT",
              "teamId": "3000202305140047",
              "timestamp": 4800,
            },
          ],
        },
        TeamProblemStatistics {
          "failedCount": 0,
          "ignoreCount": 0,
          "isFirstSolved": false,
          "isSolved": false,
          "pendingCount": 0,
          "problem": Problem {
            "balloonColor": {
              "background_color": "rgba(38, 185, 60, 0.7)",
              "color": "#fff",
            },
            "id": "3",
            "label": "D",
            "memoryLimit": undefined,
            "name": "",
            "statistics": {
              "acceptedNum": 1,
              "pendingNum": 0,
              "rejectedNum": 2,
              "submittedNum": 3,
            },
            "timeLimit": undefined,
          },
          "solvedTimestamp": 0,
          "submissions": [],
        },
        TeamProblemStatistics {
          "failedCount": 0,
          "ignoreCount": 0,
          "isFirstSolved": false,
          "isSolved": true,
          "pendingCount": 0,
          "problem": Problem {
            "balloonColor": {
              "background_color": "rgba(239, 217, 9, 0.7)",
              "color": "#000",
            },
            "id": "4",
            "label": "E",
            "memoryLimit": undefined,
            "name": "",
            "statistics": {
              "acceptedNum": 126,
              "pendingNum": 0,
              "rejectedNum": 78,
              "submittedNum": 207,
            },
            "timeLimit": undefined,
          },
          "solvedTimestamp": 300,
          "submissions": [
            Submission {
              "id": "4",
              "isIgnore": false,
              "problemId": "4",
              "status": "CORRECT",
              "teamId": "3000202305140047",
              "timestamp": 300,
            },
          ],
        },
        TeamProblemStatistics {
          "failedCount": 0,
          "ignoreCount": 0,
          "isFirstSolved": true,
          "isSolved": true,
          "pendingCount": 0,
          "problem": Problem {
            "balloonColor": {
              "background_color": "rgba(243, 88, 20, 0.7)",
              "color": "#fff",
            },
            "id": "5",
            "label": "F",
            "memoryLimit": undefined,
            "name": "",
            "statistics": {
              "acceptedNum": 125,
              "pendingNum": 0,
              "rejectedNum": 147,
              "submittedNum": 275,
            },
            "timeLimit": undefined,
          },
          "solvedTimestamp": 1200,
          "submissions": [
            Submission {
              "id": "121",
              "isIgnore": false,
              "problemId": "5",
              "status": "CORRECT",
              "teamId": "3000202305140047",
              "timestamp": 1200,
            },
          ],
        },
        TeamProblemStatistics {
          "failedCount": 0,
          "ignoreCount": 0,
          "isFirstSolved": false,
          "isSolved": false,
          "pendingCount": 0,
          "problem": Problem {
            "balloonColor": {
              "background_color": "rgba(12, 76, 138, 0.7)",
              "color": "#fff",
            },
            "id": "6",
            "label": "G",
            "memoryLimit": undefined,
            "name": "",
            "statistics": {
              "acceptedNum": 0,
              "pendingNum": 0,
              "rejectedNum": 2,
              "submittedNum": 2,
            },
            "timeLimit": undefined,
          },
          "solvedTimestamp": 0,
          "submissions": [],
        },
        TeamProblemStatistics {
          "failedCount": 1,
          "ignoreCount": 0,
          "isFirstSolved": true,
          "isSolved": true,
          "pendingCount": 0,
          "problem": Problem {
            "balloonColor": {
              "background_color": "rgba(156, 155, 155, 0.7)",
              "color": "#fff",
            },
            "id": "7",
            "label": "H",
            "memoryLimit": undefined,
            "name": "",
            "statistics": {
              "acceptedNum": 6,
              "pendingNum": 0,
              "rejectedNum": 40,
              "submittedNum": 46,
            },
            "timeLimit": undefined,
          },
          "solvedTimestamp": 7680,
          "submissions": [
            Submission {
              "id": "669",
              "isIgnore": false,
              "problemId": "7",
              "status": "REJECTED",
              "teamId": "3000202305140047",
              "timestamp": 7560,
            },
            Submission {
              "id": "685",
              "isIgnore": false,
              "problemId": "7",
              "status": "CORRECT",
              "teamId": "3000202305140047",
              "timestamp": 7680,
            },
          ],
        },
        TeamProblemStatistics {
          "failedCount": 1,
          "ignoreCount": 0,
          "isFirstSolved": false,
          "isSolved": true,
          "pendingCount": 0,
          "problem": Problem {
            "balloonColor": {
              "background_color": "rgba(4, 154, 115, 0.7)",
              "color": "#fff",
            },
            "id": "8",
            "label": "I",
            "memoryLimit": undefined,
            "name": "",
            "statistics": {
              "acceptedNum": 2,
              "pendingNum": 0,
              "rejectedNum": 10,
              "submittedNum": 12,
            },
            "timeLimit": undefined,
          },
          "solvedTimestamp": 17460,
          "submissions": [
            Submission {
              "id": "1608",
              "isIgnore": false,
              "problemId": "8",
              "status": "REJECTED",
              "teamId": "3000202305140047",
              "timestamp": 17400,
            },
            Submission {
              "id": "1632",
              "isIgnore": false,
              "problemId": "8",
              "status": "CORRECT",
              "teamId": "3000202305140047",
              "timestamp": 17460,
            },
          ],
        },
        TeamProblemStatistics {
          "failedCount": 1,
          "ignoreCount": 0,
          "isFirstSolved": false,
          "isSolved": true,
          "pendingCount": 0,
          "problem": Problem {
            "balloonColor": {
              "background_color": "rgba(159, 19, 236, 0.7)",
              "color": "#fff",
            },
            "id": "9",
            "label": "J",
            "memoryLimit": undefined,
            "name": "",
            "statistics": {
              "acceptedNum": 108,
              "pendingNum": 0,
              "rejectedNum": 329,
              "submittedNum": 441,
            },
            "timeLimit": undefined,
          },
          "solvedTimestamp": 2760,
          "submissions": [
            Submission {
              "id": "213",
              "isIgnore": false,
              "problemId": "9",
              "status": "REJECTED",
              "teamId": "3000202305140047",
              "timestamp": 2520,
            },
            Submission {
              "id": "237",
              "isIgnore": false,
              "problemId": "9",
              "status": "CORRECT",
              "teamId": "3000202305140047",
              "timestamp": 2760,
            },
          ],
        },
        TeamProblemStatistics {
          "failedCount": 3,
          "ignoreCount": 0,
          "isFirstSolved": true,
          "isSolved": true,
          "pendingCount": 0,
          "problem": Problem {
            "balloonColor": {
              "background_color": "rgba(42, 197, 202, 0.7)",
              "color": "#000",
            },
            "id": "10",
            "label": "K",
            "memoryLimit": undefined,
            "name": "",
            "statistics": {
              "acceptedNum": 1,
              "pendingNum": 0,
              "rejectedNum": 7,
              "submittedNum": 8,
            },
            "timeLimit": undefined,
          },
          "solvedTimestamp": 14280,
          "submissions": [
            Submission {
              "id": "1135",
              "isIgnore": false,
              "problemId": "10",
              "status": "REJECTED",
              "teamId": "3000202305140047",
              "timestamp": 13860,
            },
            Submission {
              "id": "1137",
              "isIgnore": false,
              "problemId": "10",
              "status": "REJECTED",
              "teamId": "3000202305140047",
              "timestamp": 13920,
            },
            Submission {
              "id": "1145",
              "isIgnore": false,
              "problemId": "10",
              "status": "REJECTED",
              "teamId": "3000202305140047",
              "timestamp": 14040,
            },
            Submission {
              "id": "1164",
              "isIgnore": false,
              "problemId": "10",
              "status": "CORRECT",
              "teamId": "3000202305140047",
              "timestamp": 14280,
            },
          ],
        },
        TeamProblemStatistics {
          "failedCount": 4,
          "ignoreCount": 0,
          "isFirstSolved": false,
          "isSolved": true,
          "pendingCount": 0,
          "problem": Problem {
            "balloonColor": {
              "background_color": "rgba(142, 56, 54, 0.7)",
              "color": "#fff",
            },
            "id": "11",
            "label": "L",
            "memoryLimit": undefined,
            "name": "",
            "statistics": {
              "acceptedNum": 48,
              "pendingNum": 0,
              "rejectedNum": 328,
              "submittedNum": 389,
            },
            "timeLimit": undefined,
          },
          "solvedTimestamp": 5760,
          "submissions": [
            Submission {
              "id": "365",
              "isIgnore": false,
              "problemId": "11",
              "status": "REJECTED",
              "teamId": "3000202305140047",
              "timestamp": 3840,
            },
            Submission {
              "id": "386",
              "isIgnore": false,
              "problemId": "11",
              "status": "REJECTED",
              "teamId": "3000202305140047",
              "timestamp": 4140,
            },
            Submission {
              "id": "405",
              "isIgnore": false,
              "problemId": "11",
              "status": "REJECTED",
              "teamId": "3000202305140047",
              "timestamp": 4380,
            },
            Submission {
              "id": "452",
              "isIgnore": false,
              "problemId": "11",
              "status": "REJECTED",
              "teamId": "3000202305140047",
              "timestamp": 4860,
            },
            Submission {
              "id": "530",
              "isIgnore": false,
              "problemId": "11",
              "status": "CORRECT",
              "teamId": "3000202305140047",
              "timestamp": 5760,
            },
          ],
        },
        TeamProblemStatistics {
          "failedCount": 0,
          "ignoreCount": 0,
          "isFirstSolved": false,
          "isSolved": true,
          "pendingCount": 0,
          "problem": Problem {
            "balloonColor": {
              "background_color": "rgba(0, 0, 0, 0.7)",
              "color": "#fff",
            },
            "id": "12",
            "label": "M",
            "memoryLimit": undefined,
            "name": "",
            "statistics": {
              "acceptedNum": 7,
              "pendingNum": 0,
              "rejectedNum": 25,
              "submittedNum": 32,
            },
            "timeLimit": undefined,
          },
          "solvedTimestamp": 9300,
          "submissions": [
            Submission {
              "id": "825",
              "isIgnore": false,
              "problemId": "12",
              "status": "CORRECT",
              "teamId": "3000202305140047",
              "timestamp": 9300,
            },
          ],
        },
      ]
    `);
    expect(rank.contest.problems).toMatchInlineSnapshot(`
      [
        Problem {
          "balloonColor": {
            "background_color": "rgba(189, 14, 14, 0.7)",
            "color": "#fff",
          },
          "id": "0",
          "label": "A",
          "memoryLimit": undefined,
          "name": "",
          "statistics": {
            "acceptedNum": 29,
            "pendingNum": 0,
            "rejectedNum": 178,
            "submittedNum": 207,
          },
          "timeLimit": undefined,
        },
        Problem {
          "balloonColor": {
            "background_color": "#951FD9",
            "color": "#fff",
          },
          "id": "1",
          "label": "B",
          "memoryLimit": undefined,
          "name": "",
          "statistics": {
            "acceptedNum": 3,
            "pendingNum": 0,
            "rejectedNum": 12,
            "submittedNum": 15,
          },
          "timeLimit": undefined,
        },
        Problem {
          "balloonColor": {
            "background_color": "rgba(255, 255, 255, 0.7)",
            "color": "#000",
          },
          "id": "2",
          "label": "C",
          "memoryLimit": undefined,
          "name": "",
          "statistics": {
            "acceptedNum": 99,
            "pendingNum": 0,
            "rejectedNum": 161,
            "submittedNum": 263,
          },
          "timeLimit": undefined,
        },
        Problem {
          "balloonColor": {
            "background_color": "rgba(38, 185, 60, 0.7)",
            "color": "#fff",
          },
          "id": "3",
          "label": "D",
          "memoryLimit": undefined,
          "name": "",
          "statistics": {
            "acceptedNum": 1,
            "pendingNum": 0,
            "rejectedNum": 2,
            "submittedNum": 3,
          },
          "timeLimit": undefined,
        },
        Problem {
          "balloonColor": {
            "background_color": "rgba(239, 217, 9, 0.7)",
            "color": "#000",
          },
          "id": "4",
          "label": "E",
          "memoryLimit": undefined,
          "name": "",
          "statistics": {
            "acceptedNum": 126,
            "pendingNum": 0,
            "rejectedNum": 78,
            "submittedNum": 207,
          },
          "timeLimit": undefined,
        },
        Problem {
          "balloonColor": {
            "background_color": "rgba(243, 88, 20, 0.7)",
            "color": "#fff",
          },
          "id": "5",
          "label": "F",
          "memoryLimit": undefined,
          "name": "",
          "statistics": {
            "acceptedNum": 125,
            "pendingNum": 0,
            "rejectedNum": 147,
            "submittedNum": 275,
          },
          "timeLimit": undefined,
        },
        Problem {
          "balloonColor": {
            "background_color": "rgba(12, 76, 138, 0.7)",
            "color": "#fff",
          },
          "id": "6",
          "label": "G",
          "memoryLimit": undefined,
          "name": "",
          "statistics": {
            "acceptedNum": 0,
            "pendingNum": 0,
            "rejectedNum": 2,
            "submittedNum": 2,
          },
          "timeLimit": undefined,
        },
        Problem {
          "balloonColor": {
            "background_color": "rgba(156, 155, 155, 0.7)",
            "color": "#fff",
          },
          "id": "7",
          "label": "H",
          "memoryLimit": undefined,
          "name": "",
          "statistics": {
            "acceptedNum": 6,
            "pendingNum": 0,
            "rejectedNum": 40,
            "submittedNum": 46,
          },
          "timeLimit": undefined,
        },
        Problem {
          "balloonColor": {
            "background_color": "rgba(4, 154, 115, 0.7)",
            "color": "#fff",
          },
          "id": "8",
          "label": "I",
          "memoryLimit": undefined,
          "name": "",
          "statistics": {
            "acceptedNum": 2,
            "pendingNum": 0,
            "rejectedNum": 10,
            "submittedNum": 12,
          },
          "timeLimit": undefined,
        },
        Problem {
          "balloonColor": {
            "background_color": "rgba(159, 19, 236, 0.7)",
            "color": "#fff",
          },
          "id": "9",
          "label": "J",
          "memoryLimit": undefined,
          "name": "",
          "statistics": {
            "acceptedNum": 108,
            "pendingNum": 0,
            "rejectedNum": 329,
            "submittedNum": 441,
          },
          "timeLimit": undefined,
        },
        Problem {
          "balloonColor": {
            "background_color": "rgba(42, 197, 202, 0.7)",
            "color": "#000",
          },
          "id": "10",
          "label": "K",
          "memoryLimit": undefined,
          "name": "",
          "statistics": {
            "acceptedNum": 1,
            "pendingNum": 0,
            "rejectedNum": 7,
            "submittedNum": 8,
          },
          "timeLimit": undefined,
        },
        Problem {
          "balloonColor": {
            "background_color": "rgba(142, 56, 54, 0.7)",
            "color": "#fff",
          },
          "id": "11",
          "label": "L",
          "memoryLimit": undefined,
          "name": "",
          "statistics": {
            "acceptedNum": 48,
            "pendingNum": 0,
            "rejectedNum": 328,
            "submittedNum": 389,
          },
          "timeLimit": undefined,
        },
        Problem {
          "balloonColor": {
            "background_color": "rgba(0, 0, 0, 0.7)",
            "color": "#fff",
          },
          "id": "12",
          "label": "M",
          "memoryLimit": undefined,
          "name": "",
          "statistics": {
            "acceptedNum": 7,
            "pendingNum": 0,
            "rejectedNum": 25,
            "submittedNum": 32,
          },
          "timeLimit": undefined,
        },
      ]
    `);

    expect(rank.teams[0]).toMatchInlineSnapshot(`
      Team {
        "coach": undefined,
        "group": [],
        "id": "3000202305140047",
        "members": [
          "王展鹏",
          "罗煜翔",
          "蒋凌宇",
        ],
        "name": "重生之我是菜狗",
        "organization": "北京大学",
        "penalty": 89820,
        "problemStatistics": [
          TeamProblemStatistics {
            "failedCount": 0,
            "ignoreCount": 0,
            "isFirstSolved": false,
            "isSolved": true,
            "pendingCount": 0,
            "problem": Problem {
              "balloonColor": {
                "background_color": "rgba(189, 14, 14, 0.7)",
                "color": "#fff",
              },
              "id": "0",
              "label": "A",
              "memoryLimit": undefined,
              "name": "",
              "statistics": {
                "acceptedNum": 29,
                "pendingNum": 0,
                "rejectedNum": 178,
                "submittedNum": 207,
              },
              "timeLimit": undefined,
            },
            "solvedTimestamp": 960,
            "submissions": [
              Submission {
                "id": "98",
                "isIgnore": false,
                "problemId": "0",
                "status": "CORRECT",
                "teamId": "3000202305140047",
                "timestamp": 960,
              },
            ],
          },
          TeamProblemStatistics {
            "failedCount": 2,
            "ignoreCount": 0,
            "isFirstSolved": true,
            "isSolved": true,
            "pendingCount": 0,
            "problem": Problem {
              "balloonColor": {
                "background_color": "#951FD9",
                "color": "#fff",
              },
              "id": "1",
              "label": "B",
              "memoryLimit": undefined,
              "name": "",
              "statistics": {
                "acceptedNum": 3,
                "pendingNum": 0,
                "rejectedNum": 12,
                "submittedNum": 15,
              },
              "timeLimit": undefined,
            },
            "solvedTimestamp": 10920,
            "submissions": [
              Submission {
                "id": "877",
                "isIgnore": false,
                "problemId": "1",
                "status": "REJECTED",
                "teamId": "3000202305140047",
                "timestamp": 10020,
              },
              Submission {
                "id": "890",
                "isIgnore": false,
                "problemId": "1",
                "status": "REJECTED",
                "teamId": "3000202305140047",
                "timestamp": 10320,
              },
              Submission {
                "id": "920",
                "isIgnore": false,
                "problemId": "1",
                "status": "CORRECT",
                "teamId": "3000202305140047",
                "timestamp": 10920,
              },
            ],
          },
          TeamProblemStatistics {
            "failedCount": 0,
            "ignoreCount": 0,
            "isFirstSolved": false,
            "isSolved": true,
            "pendingCount": 0,
            "problem": Problem {
              "balloonColor": {
                "background_color": "rgba(255, 255, 255, 0.7)",
                "color": "#000",
              },
              "id": "2",
              "label": "C",
              "memoryLimit": undefined,
              "name": "",
              "statistics": {
                "acceptedNum": 99,
                "pendingNum": 0,
                "rejectedNum": 161,
                "submittedNum": 263,
              },
              "timeLimit": undefined,
            },
            "solvedTimestamp": 4800,
            "submissions": [
              Submission {
                "id": "438",
                "isIgnore": false,
                "problemId": "2",
                "status": "CORRECT",
                "teamId": "3000202305140047",
                "timestamp": 4800,
              },
            ],
          },
          TeamProblemStatistics {
            "failedCount": 0,
            "ignoreCount": 0,
            "isFirstSolved": false,
            "isSolved": false,
            "pendingCount": 0,
            "problem": Problem {
              "balloonColor": {
                "background_color": "rgba(38, 185, 60, 0.7)",
                "color": "#fff",
              },
              "id": "3",
              "label": "D",
              "memoryLimit": undefined,
              "name": "",
              "statistics": {
                "acceptedNum": 1,
                "pendingNum": 0,
                "rejectedNum": 2,
                "submittedNum": 3,
              },
              "timeLimit": undefined,
            },
            "solvedTimestamp": 0,
            "submissions": [],
          },
          TeamProblemStatistics {
            "failedCount": 0,
            "ignoreCount": 0,
            "isFirstSolved": false,
            "isSolved": true,
            "pendingCount": 0,
            "problem": Problem {
              "balloonColor": {
                "background_color": "rgba(239, 217, 9, 0.7)",
                "color": "#000",
              },
              "id": "4",
              "label": "E",
              "memoryLimit": undefined,
              "name": "",
              "statistics": {
                "acceptedNum": 126,
                "pendingNum": 0,
                "rejectedNum": 78,
                "submittedNum": 207,
              },
              "timeLimit": undefined,
            },
            "solvedTimestamp": 300,
            "submissions": [
              Submission {
                "id": "4",
                "isIgnore": false,
                "problemId": "4",
                "status": "CORRECT",
                "teamId": "3000202305140047",
                "timestamp": 300,
              },
            ],
          },
          TeamProblemStatistics {
            "failedCount": 0,
            "ignoreCount": 0,
            "isFirstSolved": true,
            "isSolved": true,
            "pendingCount": 0,
            "problem": Problem {
              "balloonColor": {
                "background_color": "rgba(243, 88, 20, 0.7)",
                "color": "#fff",
              },
              "id": "5",
              "label": "F",
              "memoryLimit": undefined,
              "name": "",
              "statistics": {
                "acceptedNum": 125,
                "pendingNum": 0,
                "rejectedNum": 147,
                "submittedNum": 275,
              },
              "timeLimit": undefined,
            },
            "solvedTimestamp": 1200,
            "submissions": [
              Submission {
                "id": "121",
                "isIgnore": false,
                "problemId": "5",
                "status": "CORRECT",
                "teamId": "3000202305140047",
                "timestamp": 1200,
              },
            ],
          },
          TeamProblemStatistics {
            "failedCount": 0,
            "ignoreCount": 0,
            "isFirstSolved": false,
            "isSolved": false,
            "pendingCount": 0,
            "problem": Problem {
              "balloonColor": {
                "background_color": "rgba(12, 76, 138, 0.7)",
                "color": "#fff",
              },
              "id": "6",
              "label": "G",
              "memoryLimit": undefined,
              "name": "",
              "statistics": {
                "acceptedNum": 0,
                "pendingNum": 0,
                "rejectedNum": 2,
                "submittedNum": 2,
              },
              "timeLimit": undefined,
            },
            "solvedTimestamp": 0,
            "submissions": [],
          },
          TeamProblemStatistics {
            "failedCount": 1,
            "ignoreCount": 0,
            "isFirstSolved": true,
            "isSolved": true,
            "pendingCount": 0,
            "problem": Problem {
              "balloonColor": {
                "background_color": "rgba(156, 155, 155, 0.7)",
                "color": "#fff",
              },
              "id": "7",
              "label": "H",
              "memoryLimit": undefined,
              "name": "",
              "statistics": {
                "acceptedNum": 6,
                "pendingNum": 0,
                "rejectedNum": 40,
                "submittedNum": 46,
              },
              "timeLimit": undefined,
            },
            "solvedTimestamp": 7680,
            "submissions": [
              Submission {
                "id": "669",
                "isIgnore": false,
                "problemId": "7",
                "status": "REJECTED",
                "teamId": "3000202305140047",
                "timestamp": 7560,
              },
              Submission {
                "id": "685",
                "isIgnore": false,
                "problemId": "7",
                "status": "CORRECT",
                "teamId": "3000202305140047",
                "timestamp": 7680,
              },
            ],
          },
          TeamProblemStatistics {
            "failedCount": 1,
            "ignoreCount": 0,
            "isFirstSolved": false,
            "isSolved": true,
            "pendingCount": 0,
            "problem": Problem {
              "balloonColor": {
                "background_color": "rgba(4, 154, 115, 0.7)",
                "color": "#fff",
              },
              "id": "8",
              "label": "I",
              "memoryLimit": undefined,
              "name": "",
              "statistics": {
                "acceptedNum": 2,
                "pendingNum": 0,
                "rejectedNum": 10,
                "submittedNum": 12,
              },
              "timeLimit": undefined,
            },
            "solvedTimestamp": 17460,
            "submissions": [
              Submission {
                "id": "1608",
                "isIgnore": false,
                "problemId": "8",
                "status": "REJECTED",
                "teamId": "3000202305140047",
                "timestamp": 17400,
              },
              Submission {
                "id": "1632",
                "isIgnore": false,
                "problemId": "8",
                "status": "CORRECT",
                "teamId": "3000202305140047",
                "timestamp": 17460,
              },
            ],
          },
          TeamProblemStatistics {
            "failedCount": 1,
            "ignoreCount": 0,
            "isFirstSolved": false,
            "isSolved": true,
            "pendingCount": 0,
            "problem": Problem {
              "balloonColor": {
                "background_color": "rgba(159, 19, 236, 0.7)",
                "color": "#fff",
              },
              "id": "9",
              "label": "J",
              "memoryLimit": undefined,
              "name": "",
              "statistics": {
                "acceptedNum": 108,
                "pendingNum": 0,
                "rejectedNum": 329,
                "submittedNum": 441,
              },
              "timeLimit": undefined,
            },
            "solvedTimestamp": 2760,
            "submissions": [
              Submission {
                "id": "213",
                "isIgnore": false,
                "problemId": "9",
                "status": "REJECTED",
                "teamId": "3000202305140047",
                "timestamp": 2520,
              },
              Submission {
                "id": "237",
                "isIgnore": false,
                "problemId": "9",
                "status": "CORRECT",
                "teamId": "3000202305140047",
                "timestamp": 2760,
              },
            ],
          },
          TeamProblemStatistics {
            "failedCount": 3,
            "ignoreCount": 0,
            "isFirstSolved": true,
            "isSolved": true,
            "pendingCount": 0,
            "problem": Problem {
              "balloonColor": {
                "background_color": "rgba(42, 197, 202, 0.7)",
                "color": "#000",
              },
              "id": "10",
              "label": "K",
              "memoryLimit": undefined,
              "name": "",
              "statistics": {
                "acceptedNum": 1,
                "pendingNum": 0,
                "rejectedNum": 7,
                "submittedNum": 8,
              },
              "timeLimit": undefined,
            },
            "solvedTimestamp": 14280,
            "submissions": [
              Submission {
                "id": "1135",
                "isIgnore": false,
                "problemId": "10",
                "status": "REJECTED",
                "teamId": "3000202305140047",
                "timestamp": 13860,
              },
              Submission {
                "id": "1137",
                "isIgnore": false,
                "problemId": "10",
                "status": "REJECTED",
                "teamId": "3000202305140047",
                "timestamp": 13920,
              },
              Submission {
                "id": "1145",
                "isIgnore": false,
                "problemId": "10",
                "status": "REJECTED",
                "teamId": "3000202305140047",
                "timestamp": 14040,
              },
              Submission {
                "id": "1164",
                "isIgnore": false,
                "problemId": "10",
                "status": "CORRECT",
                "teamId": "3000202305140047",
                "timestamp": 14280,
              },
            ],
          },
          TeamProblemStatistics {
            "failedCount": 4,
            "ignoreCount": 0,
            "isFirstSolved": false,
            "isSolved": true,
            "pendingCount": 0,
            "problem": Problem {
              "balloonColor": {
                "background_color": "rgba(142, 56, 54, 0.7)",
                "color": "#fff",
              },
              "id": "11",
              "label": "L",
              "memoryLimit": undefined,
              "name": "",
              "statistics": {
                "acceptedNum": 48,
                "pendingNum": 0,
                "rejectedNum": 328,
                "submittedNum": 389,
              },
              "timeLimit": undefined,
            },
            "solvedTimestamp": 5760,
            "submissions": [
              Submission {
                "id": "365",
                "isIgnore": false,
                "problemId": "11",
                "status": "REJECTED",
                "teamId": "3000202305140047",
                "timestamp": 3840,
              },
              Submission {
                "id": "386",
                "isIgnore": false,
                "problemId": "11",
                "status": "REJECTED",
                "teamId": "3000202305140047",
                "timestamp": 4140,
              },
              Submission {
                "id": "405",
                "isIgnore": false,
                "problemId": "11",
                "status": "REJECTED",
                "teamId": "3000202305140047",
                "timestamp": 4380,
              },
              Submission {
                "id": "452",
                "isIgnore": false,
                "problemId": "11",
                "status": "REJECTED",
                "teamId": "3000202305140047",
                "timestamp": 4860,
              },
              Submission {
                "id": "530",
                "isIgnore": false,
                "problemId": "11",
                "status": "CORRECT",
                "teamId": "3000202305140047",
                "timestamp": 5760,
              },
            ],
          },
          TeamProblemStatistics {
            "failedCount": 0,
            "ignoreCount": 0,
            "isFirstSolved": false,
            "isSolved": true,
            "pendingCount": 0,
            "problem": Problem {
              "balloonColor": {
                "background_color": "rgba(0, 0, 0, 0.7)",
                "color": "#fff",
              },
              "id": "12",
              "label": "M",
              "memoryLimit": undefined,
              "name": "",
              "statistics": {
                "acceptedNum": 7,
                "pendingNum": 0,
                "rejectedNum": 25,
                "submittedNum": 32,
              },
              "timeLimit": undefined,
            },
            "solvedTimestamp": 9300,
            "submissions": [
              Submission {
                "id": "825",
                "isIgnore": false,
                "problemId": "12",
                "status": "CORRECT",
                "teamId": "3000202305140047",
                "timestamp": 9300,
              },
            ],
          },
        ],
        "problemStatisticsMap": Map {
          "0" => TeamProblemStatistics {
            "failedCount": 0,
            "ignoreCount": 0,
            "isFirstSolved": false,
            "isSolved": true,
            "pendingCount": 0,
            "problem": Problem {
              "balloonColor": {
                "background_color": "rgba(189, 14, 14, 0.7)",
                "color": "#fff",
              },
              "id": "0",
              "label": "A",
              "memoryLimit": undefined,
              "name": "",
              "statistics": {
                "acceptedNum": 29,
                "pendingNum": 0,
                "rejectedNum": 178,
                "submittedNum": 207,
              },
              "timeLimit": undefined,
            },
            "solvedTimestamp": 960,
            "submissions": [
              Submission {
                "id": "98",
                "isIgnore": false,
                "problemId": "0",
                "status": "CORRECT",
                "teamId": "3000202305140047",
                "timestamp": 960,
              },
            ],
          },
          "1" => TeamProblemStatistics {
            "failedCount": 2,
            "ignoreCount": 0,
            "isFirstSolved": true,
            "isSolved": true,
            "pendingCount": 0,
            "problem": Problem {
              "balloonColor": {
                "background_color": "#951FD9",
                "color": "#fff",
              },
              "id": "1",
              "label": "B",
              "memoryLimit": undefined,
              "name": "",
              "statistics": {
                "acceptedNum": 3,
                "pendingNum": 0,
                "rejectedNum": 12,
                "submittedNum": 15,
              },
              "timeLimit": undefined,
            },
            "solvedTimestamp": 10920,
            "submissions": [
              Submission {
                "id": "877",
                "isIgnore": false,
                "problemId": "1",
                "status": "REJECTED",
                "teamId": "3000202305140047",
                "timestamp": 10020,
              },
              Submission {
                "id": "890",
                "isIgnore": false,
                "problemId": "1",
                "status": "REJECTED",
                "teamId": "3000202305140047",
                "timestamp": 10320,
              },
              Submission {
                "id": "920",
                "isIgnore": false,
                "problemId": "1",
                "status": "CORRECT",
                "teamId": "3000202305140047",
                "timestamp": 10920,
              },
            ],
          },
          "2" => TeamProblemStatistics {
            "failedCount": 0,
            "ignoreCount": 0,
            "isFirstSolved": false,
            "isSolved": true,
            "pendingCount": 0,
            "problem": Problem {
              "balloonColor": {
                "background_color": "rgba(255, 255, 255, 0.7)",
                "color": "#000",
              },
              "id": "2",
              "label": "C",
              "memoryLimit": undefined,
              "name": "",
              "statistics": {
                "acceptedNum": 99,
                "pendingNum": 0,
                "rejectedNum": 161,
                "submittedNum": 263,
              },
              "timeLimit": undefined,
            },
            "solvedTimestamp": 4800,
            "submissions": [
              Submission {
                "id": "438",
                "isIgnore": false,
                "problemId": "2",
                "status": "CORRECT",
                "teamId": "3000202305140047",
                "timestamp": 4800,
              },
            ],
          },
          "3" => TeamProblemStatistics {
            "failedCount": 0,
            "ignoreCount": 0,
            "isFirstSolved": false,
            "isSolved": false,
            "pendingCount": 0,
            "problem": Problem {
              "balloonColor": {
                "background_color": "rgba(38, 185, 60, 0.7)",
                "color": "#fff",
              },
              "id": "3",
              "label": "D",
              "memoryLimit": undefined,
              "name": "",
              "statistics": {
                "acceptedNum": 1,
                "pendingNum": 0,
                "rejectedNum": 2,
                "submittedNum": 3,
              },
              "timeLimit": undefined,
            },
            "solvedTimestamp": 0,
            "submissions": [],
          },
          "4" => TeamProblemStatistics {
            "failedCount": 0,
            "ignoreCount": 0,
            "isFirstSolved": false,
            "isSolved": true,
            "pendingCount": 0,
            "problem": Problem {
              "balloonColor": {
                "background_color": "rgba(239, 217, 9, 0.7)",
                "color": "#000",
              },
              "id": "4",
              "label": "E",
              "memoryLimit": undefined,
              "name": "",
              "statistics": {
                "acceptedNum": 126,
                "pendingNum": 0,
                "rejectedNum": 78,
                "submittedNum": 207,
              },
              "timeLimit": undefined,
            },
            "solvedTimestamp": 300,
            "submissions": [
              Submission {
                "id": "4",
                "isIgnore": false,
                "problemId": "4",
                "status": "CORRECT",
                "teamId": "3000202305140047",
                "timestamp": 300,
              },
            ],
          },
          "5" => TeamProblemStatistics {
            "failedCount": 0,
            "ignoreCount": 0,
            "isFirstSolved": true,
            "isSolved": true,
            "pendingCount": 0,
            "problem": Problem {
              "balloonColor": {
                "background_color": "rgba(243, 88, 20, 0.7)",
                "color": "#fff",
              },
              "id": "5",
              "label": "F",
              "memoryLimit": undefined,
              "name": "",
              "statistics": {
                "acceptedNum": 125,
                "pendingNum": 0,
                "rejectedNum": 147,
                "submittedNum": 275,
              },
              "timeLimit": undefined,
            },
            "solvedTimestamp": 1200,
            "submissions": [
              Submission {
                "id": "121",
                "isIgnore": false,
                "problemId": "5",
                "status": "CORRECT",
                "teamId": "3000202305140047",
                "timestamp": 1200,
              },
            ],
          },
          "6" => TeamProblemStatistics {
            "failedCount": 0,
            "ignoreCount": 0,
            "isFirstSolved": false,
            "isSolved": false,
            "pendingCount": 0,
            "problem": Problem {
              "balloonColor": {
                "background_color": "rgba(12, 76, 138, 0.7)",
                "color": "#fff",
              },
              "id": "6",
              "label": "G",
              "memoryLimit": undefined,
              "name": "",
              "statistics": {
                "acceptedNum": 0,
                "pendingNum": 0,
                "rejectedNum": 2,
                "submittedNum": 2,
              },
              "timeLimit": undefined,
            },
            "solvedTimestamp": 0,
            "submissions": [],
          },
          "7" => TeamProblemStatistics {
            "failedCount": 1,
            "ignoreCount": 0,
            "isFirstSolved": true,
            "isSolved": true,
            "pendingCount": 0,
            "problem": Problem {
              "balloonColor": {
                "background_color": "rgba(156, 155, 155, 0.7)",
                "color": "#fff",
              },
              "id": "7",
              "label": "H",
              "memoryLimit": undefined,
              "name": "",
              "statistics": {
                "acceptedNum": 6,
                "pendingNum": 0,
                "rejectedNum": 40,
                "submittedNum": 46,
              },
              "timeLimit": undefined,
            },
            "solvedTimestamp": 7680,
            "submissions": [
              Submission {
                "id": "669",
                "isIgnore": false,
                "problemId": "7",
                "status": "REJECTED",
                "teamId": "3000202305140047",
                "timestamp": 7560,
              },
              Submission {
                "id": "685",
                "isIgnore": false,
                "problemId": "7",
                "status": "CORRECT",
                "teamId": "3000202305140047",
                "timestamp": 7680,
              },
            ],
          },
          "8" => TeamProblemStatistics {
            "failedCount": 1,
            "ignoreCount": 0,
            "isFirstSolved": false,
            "isSolved": true,
            "pendingCount": 0,
            "problem": Problem {
              "balloonColor": {
                "background_color": "rgba(4, 154, 115, 0.7)",
                "color": "#fff",
              },
              "id": "8",
              "label": "I",
              "memoryLimit": undefined,
              "name": "",
              "statistics": {
                "acceptedNum": 2,
                "pendingNum": 0,
                "rejectedNum": 10,
                "submittedNum": 12,
              },
              "timeLimit": undefined,
            },
            "solvedTimestamp": 17460,
            "submissions": [
              Submission {
                "id": "1608",
                "isIgnore": false,
                "problemId": "8",
                "status": "REJECTED",
                "teamId": "3000202305140047",
                "timestamp": 17400,
              },
              Submission {
                "id": "1632",
                "isIgnore": false,
                "problemId": "8",
                "status": "CORRECT",
                "teamId": "3000202305140047",
                "timestamp": 17460,
              },
            ],
          },
          "9" => TeamProblemStatistics {
            "failedCount": 1,
            "ignoreCount": 0,
            "isFirstSolved": false,
            "isSolved": true,
            "pendingCount": 0,
            "problem": Problem {
              "balloonColor": {
                "background_color": "rgba(159, 19, 236, 0.7)",
                "color": "#fff",
              },
              "id": "9",
              "label": "J",
              "memoryLimit": undefined,
              "name": "",
              "statistics": {
                "acceptedNum": 108,
                "pendingNum": 0,
                "rejectedNum": 329,
                "submittedNum": 441,
              },
              "timeLimit": undefined,
            },
            "solvedTimestamp": 2760,
            "submissions": [
              Submission {
                "id": "213",
                "isIgnore": false,
                "problemId": "9",
                "status": "REJECTED",
                "teamId": "3000202305140047",
                "timestamp": 2520,
              },
              Submission {
                "id": "237",
                "isIgnore": false,
                "problemId": "9",
                "status": "CORRECT",
                "teamId": "3000202305140047",
                "timestamp": 2760,
              },
            ],
          },
          "10" => TeamProblemStatistics {
            "failedCount": 3,
            "ignoreCount": 0,
            "isFirstSolved": true,
            "isSolved": true,
            "pendingCount": 0,
            "problem": Problem {
              "balloonColor": {
                "background_color": "rgba(42, 197, 202, 0.7)",
                "color": "#000",
              },
              "id": "10",
              "label": "K",
              "memoryLimit": undefined,
              "name": "",
              "statistics": {
                "acceptedNum": 1,
                "pendingNum": 0,
                "rejectedNum": 7,
                "submittedNum": 8,
              },
              "timeLimit": undefined,
            },
            "solvedTimestamp": 14280,
            "submissions": [
              Submission {
                "id": "1135",
                "isIgnore": false,
                "problemId": "10",
                "status": "REJECTED",
                "teamId": "3000202305140047",
                "timestamp": 13860,
              },
              Submission {
                "id": "1137",
                "isIgnore": false,
                "problemId": "10",
                "status": "REJECTED",
                "teamId": "3000202305140047",
                "timestamp": 13920,
              },
              Submission {
                "id": "1145",
                "isIgnore": false,
                "problemId": "10",
                "status": "REJECTED",
                "teamId": "3000202305140047",
                "timestamp": 14040,
              },
              Submission {
                "id": "1164",
                "isIgnore": false,
                "problemId": "10",
                "status": "CORRECT",
                "teamId": "3000202305140047",
                "timestamp": 14280,
              },
            ],
          },
          "11" => TeamProblemStatistics {
            "failedCount": 4,
            "ignoreCount": 0,
            "isFirstSolved": false,
            "isSolved": true,
            "pendingCount": 0,
            "problem": Problem {
              "balloonColor": {
                "background_color": "rgba(142, 56, 54, 0.7)",
                "color": "#fff",
              },
              "id": "11",
              "label": "L",
              "memoryLimit": undefined,
              "name": "",
              "statistics": {
                "acceptedNum": 48,
                "pendingNum": 0,
                "rejectedNum": 328,
                "submittedNum": 389,
              },
              "timeLimit": undefined,
            },
            "solvedTimestamp": 5760,
            "submissions": [
              Submission {
                "id": "365",
                "isIgnore": false,
                "problemId": "11",
                "status": "REJECTED",
                "teamId": "3000202305140047",
                "timestamp": 3840,
              },
              Submission {
                "id": "386",
                "isIgnore": false,
                "problemId": "11",
                "status": "REJECTED",
                "teamId": "3000202305140047",
                "timestamp": 4140,
              },
              Submission {
                "id": "405",
                "isIgnore": false,
                "problemId": "11",
                "status": "REJECTED",
                "teamId": "3000202305140047",
                "timestamp": 4380,
              },
              Submission {
                "id": "452",
                "isIgnore": false,
                "problemId": "11",
                "status": "REJECTED",
                "teamId": "3000202305140047",
                "timestamp": 4860,
              },
              Submission {
                "id": "530",
                "isIgnore": false,
                "problemId": "11",
                "status": "CORRECT",
                "teamId": "3000202305140047",
                "timestamp": 5760,
              },
            ],
          },
          "12" => TeamProblemStatistics {
            "failedCount": 0,
            "ignoreCount": 0,
            "isFirstSolved": false,
            "isSolved": true,
            "pendingCount": 0,
            "problem": Problem {
              "balloonColor": {
                "background_color": "rgba(0, 0, 0, 0.7)",
                "color": "#fff",
              },
              "id": "12",
              "label": "M",
              "memoryLimit": undefined,
              "name": "",
              "statistics": {
                "acceptedNum": 7,
                "pendingNum": 0,
                "rejectedNum": 25,
                "submittedNum": 32,
              },
              "timeLimit": undefined,
            },
            "solvedTimestamp": 9300,
            "submissions": [
              Submission {
                "id": "825",
                "isIgnore": false,
                "problemId": "12",
                "status": "CORRECT",
                "teamId": "3000202305140047",
                "timestamp": 9300,
              },
            ],
          },
        },
        "rank": 1,
        "solvedProblemNum": 11,
        "tag": [],
      }
    `);

    expect(JSON.stringify(rank)).toMatchSnapshot();
  });
});
