// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  loader: string;
  'loader-21': string;
  loader21: string;
}
export const cssExports: CssExports;
export default cssExports;
