// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'second-level-menu-item': string;
  'second-level-menu-item-current': string;
  'second-level-menu-list': string;
}
export const cssExports: CssExports;
export default cssExports;
