# yaml-language-server: $schema=https://json-schema.org/draft-07/schema#
name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  node-version: 24.x

jobs:
  node-lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v5
        with:
          node-version: ${{ env.node-version }}
          registry-url: https://registry.npmjs.org/
          cache: pnpm

      - name: Install and Build
        run: |
          pnpm i
          pnpm build

      - name: Enable 404.html
        run: |
          cp ./packages/apps/board/dist/index.html ./packages/apps/board/dist/404.html

      - name: Lint
        run: |
          pnpm run lint

      - name: Test
        run: |
          pnpm run test

  python-lint-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./python
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - name: Install
        run: |
          uv python install
          uv install

      - name: Lint
        run: uv run ruff check

      - name: Test
        run: uv run pytest
